name: CI Pipeline

on:
  push:
    branches: 
      - main           # Trigger on pushes to 'main'
  pull_request:
    branches: 
      - main           # Trigger on pull requests to 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run your build steps
        run: echo "Running on branch ${{ github.ref_name }}"
      
      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag swimpyblaq92/chima:${{ env.IMAGE_TAG }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push swimpyblaq92/chima:${{ env.IMAGE_TAG }}

    
