name: CI Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag swimpyblaq92/chima:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push swimpyblaq92/chima:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}     # Your VM's IP address
          username: ${{ secrets.VM_USER }} # Your VM's SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Ensure this matches GitHub Secrets
          script: |
            echo "Pulling latest image..."
            docker pull swimpyblaq92/chima:latest
            
            echo "Stopping existing container..."
            docker stop hello_container || true
            docker rm hello_container || true
            
            echo "Starting new container..."
            docker run -d --name hello_container -p 80:80 swimpyblaq92/chima:latest
